default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  port: "5432"
  host: db
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rails_auth_dev

test:
  <<: *default
  database: rails_auth_test

production:
  <<: *default
  database: rails_auth_prod
